# version : "3.8"
# services:

#   app:
#     image: elielecas/us_sba-app
#     depends_on:
#       - postgres_db
#     ports:
#       - 8001:8001
#     env_file:
#       - app/.env
    
#   postgres_db:
#     image: postgres 
#     restart: always
#     env_file:
#       - app/.env 
#     ports:
#       - 5432:5432
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
      
#   api:
#     image: elielecas/us_sba-api
#     ports:
#       - 8000:8000
    

# volumes:
#   postgres_data:


version : "3.8"
services:
  app:
    depends_on:
      - postgres_db
    ports:
      - 80:80
    env_file:
      - app/.env
    build: 
      context: ./app/
      dockerfile: Dockerfile  
    volumes:
      - ./app/:/app/
  postgres_db:
    image: postgres 
    restart: always
    env_file:
      - app/.env 
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  api:
    ports:
      - 8000:8000
    build:
      context: ./api/
      dockerfile: Dockerfile 

volumes:
  postgres_data: