version : "3.8"
services:
  app:
    depends_on:
      - postgres_db
    ports:
      - 8001:8001
    env_file:
      - app/.env
    build: 
      context: ./app/
      dockerfile: Dockerfile      
  postgres_db:
    image: postgres 
    restart: always
    env_file:
      - app/.env 
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  api:
    ports:
      - 8000:8000
    build:
      context: ./api/
      dockerfile: Dockerfile 

volumes:
  postgres_data: