# Generated by Django 4.2.10 on 2024-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictApi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("State", models.CharField(max_length=100)),
                ("Zip", models.IntegerField()),
                ("BankState", models.CharField(max_length=100)),
                ("ApprovalFY", models.IntegerField()),
                ("Term", models.IntegerField()),
                ("GrAppv", models.IntegerField()),
                ("SBA_Appv", models.IntegerField()),
            ],
        ),
    ]
