# Generated by Django 4.1 on 2024-03-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_predictapi_approvalfy_alter_predictapi_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictapi',
            name='ApprovalFY',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictapi',
            name='Term',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictapi',
            name='Zip',
            field=models.IntegerField(),
        ),
    ]
